services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - "./02-test-intermediate/01-vol-pgserv-ny-taxi:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
    networks:
      - pg-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"
    volumes:
      - "./02-test-intermediate/02-vol-pgadmin:/var/lib/pgadmin:rw"
    depends_on:
      - pgdatabase
    networks:
      - pg-network
      
networks:
  pg-network:

